## path to tools ##
readCounterScript:  /Path/to/readCounter*
ichorCNA_rscript:  /Path/to/ichorCNA/scripts/runIchorCNA.R*
ichorCNA_libdir:  /Path/to/ichorCNA/R/*
pyCountScript:  /Path/to/TitanCNA/scripts/snakemake/code/countPysam.py*
TitanCNA_rscript: /Path/to/TitanCNA/scripts/R_scripts/titanCNA.R*
TitanCNA_selectSolutionRscript: /Path/to/TitanCNA/scripts/R_scripts/selectSolution.R*
TitanCNA_libdir:  /Path/to/TitanCNA/R/*

## path to reference files ##
ichorCNA_exons: NULL
ichorCNA_centromere: /Path/to/ichorCNA/inst/extdata/GRCh37.p13_centromere_UCSC-gapTable.txt*
refFasta: /Path/to/GRCh37/Sequence/WholeGenomeFasta/genome.fa*
snpDB: /Path/to/hapmap_3.3.b37.vcf*
TitanCNA_centromere:  /Path/to/ichorCNA/inst/extdata/GRCh37.p13_centromere_UCSC-gapTable.txt*

## params for each step ##

## read depth params ##
chrs:
  1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,X,Y
binSize:  100000

## ichorCNA params ##
ichorCNA_gcWig: /Path/to/ichorCNA/inst/extdata/gc_hg19_100kb.wig*
ichorCNA_mapWig:  /Path/to/ichorCNA/inst/extdata/map_hg19_100kb.wig*
ichorCNA_chrs:  c(1:22, \"X\")
ichorCNA_chrTrain:  c(1:22)  
ichorCNA_normal:  c(0.5)  
ichorCNA_ploidy:  c(2,3)  
ichorCNA_estimateNormal:  TRUE
ichorCNA_estimatePloidy:  TRUE
ichorCNA_estimateClonality: TRUE
ichorCNA_scStates:  c(1,3)
ichorCNA_maxCN:  8
ichorCNA_includeHOMD: FALSE
ichorCNA_txnE:  0.9999
ichorCNA_txnStrength:  10000
ichorCNA_plotFileType:  png
ichorCNA_plotYlim:  c(-2,4)

## allele counts - samtools, pysam ##
map_quality:  10
base_quality: 10
vcf_quality:  100

## TitanCNA params ##
TitanCNA_numCores: 1
TitanCNA_maxNumClonalClusters: 2
TitanCNA_chrs:  c(1:22, \"X\")
TitanCNA_normalInit: 0.5
TitanCNA_maxPloidy: 2
TitanCNA_estimateNormal:  map
TitanCNA_estimatePloidy:  TRUE
TitanCNA_estimateClonality: TRUE
TitanCNA_alleleModel: binomial
TitanCNA_alphaK:  20000
TitanCNA_alphaR:  20000
TitanCNA_txnExpLen: 1e15
TitanCNA_plotYlim:  c(-2,4)
TitanCNA_solutionThreshold: 0.05
TitanCNA_minDepth: 5

